# Generated by Django 6.0.3 on 2026-03-20 02:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=64)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_in_location', models.CharField(max_length=255)),
                ('check_in_photo', models.ImageField(upload_to='attendance/checkins/')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_photo', models.ImageField(upload_to='attendance/checkouts/')),
                ('total_shift_time', models.DurationField(blank=True, null=True)),
                ('check_in', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_out', to='scheduling.checkin')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=64)),
                ('subject_topic', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='upcoming', max_length=16)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
