# Generated by Django 6.0.3 on 2026-03-20 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='check_in',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='scheduling.checkin'),
        ),
    ]
