# Generated by Django 6.0.3 on 2026-03-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_student_split_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA')], default='SD', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
