# Generated by Django 6.0.3 on 2026-03-21 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_checkin_description_schedule_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='upcoming', max_length=16),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_schedule_requests', to='scheduling.schedule')),
                ('old_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_schedule_requests', to='scheduling.schedule')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
    ]
