# Generated by Django 5.2.4 on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_emailblastrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='extension',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='new_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.PROTECT, related_name='new_schedule_requests', to='scheduling.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('done', 'Done'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('extended', 'Extended'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='upcoming', max_length=16),
        ),
    ]
