# Generated by Django 5.2.12 on 2026-04-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0017_remove_request_description_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("done", "Done"),
                    ("autodone", "Autodone"),
                    ("missed", "Missed"),
                    ("cancelled", "Cancelled"),
                    ("rescheduled", "Rescheduled"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                ],
                default="upcoming",
                max_length=16,
            ),
        ),
    ]
