# Generated by Django 5.1.8 on 2026-05-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0018_alter_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
